### ISSUE TITLE
Not pulling cover art, song title, or artist from Spotify

### ISSUE THREAD

**Issue by TalostheCat** [MarcoPixel/Monstercat-Visualizer#191]
### Description

As the title says, that's all I see. The cover is just white with the Monstercat logo with a dropshadow and the text says N/A - N/A

### Versions

* Rainmeter Version: 4.2.0r3111
* OS Version: Windows 10 Home 1803 x64 (build 17134)
* Skin Version: 2.0.2
* Spotify DLL Version: 2.1.5
* Spotify Program Version: 
![image](https://user-images.githubusercontent.com/41400936/42912726-e868977a-8abe-11e8-90b1-3e13e42fca28.png)

### Additional notes/images
![image](https://user-images.githubusercontent.com/41400936/42912623-575f2d02-8abe-11e8-8d81-1d18c273c96b.png)

**Comment by SoDaBearJess** [comment]
I just begun to start having the same issue. Did your Spotify update anytime in the past couple of days?

**Comment by TalostheCat** [comment]
I have a feeling that's exactly what happened

**Comment by OTEKKENDURE** [comment]
I have a problem exactly like this within the past 9 hours I can't get song information, cover art or progress indicator. I tried many things and gave up. It's something to do with a change in Spotify's code at their end.

**Comment by GzpyINFT** [comment]
@OTEKKENDURE Its the SpotifyPlugin.dll outdated I'm pretty sure.

**Comment by OTEKKENDURE** [comment]
Hey thanks @GzpyINFT. I wish Spotify could notify the user as well in the update process. It's all silent background stuff and I have to manually check their sites patch notes for if they updated in the last 24 hours or not. All I can do is wait for an update from here.

**Comment by GzpyINFT** [comment]
Np.

**Comment by P1X3L0V4** [comment]
I can confirm that covers are not showing up correctly on Spotify version 1.0.85.259.g4ab01679

**Comment by DePianoman** [comment]
Confirmed on Spotify 1.0.85.257.g0f8531bd

**Comment by MarcoPixel** [comment]
We know about this issue and we'll hope that it can be fixed as soon as possible. For now we can only wait and see if there will be an update for the SpotifyPlugin / SpotifyAPI-Net.

 For more information, please visit https://github.com/JohnnyCrazy/SpotifyAPI-NET/issues/254 or https://github.com/RobertFrydenlund/SpotifyPlugin/issues/18 as the issue lies on Spotify removing the local API and replacing it with their new web api.

**Comment by th3an7** [comment]
Had the same issue... It should work again with https://github.com/RobertFrydenlund/SpotifyPlugin/releases/tag/v2.1.6-beta.2

**Comment by Permanently** [comment]
Tried this, and it works... for 30 seconds. After that Rainmeter just crashes and I have to relaunch only for the same crash to repeat itself. No idea if that's just the visualiser I'm using or if it's my computer.

**Comment by DominykasPetke** [comment]
Well, I don't know if Spicetify (another Rainmeter plug-in) affects anything here, but I have both that and this visualiser with the WebNowPlaying mode and since Spotify is a Chromium based app now, it does pull the artist, title and the cover art successfully. The only things not working correctly are the song length and now @ point in the song labels.

**Comment by Ein6tein** [comment]
https://github.com/RobertFrydenlund/SpotifyPlugin/releases

Latest version almost works - it periodically drops info, but periodically shows it again

**Comment by RobertFrydenlund** [comment]
SpotifyPlugin development is discontinued, see https://github.com/RobertFrydenlund/SpotifyPlugin/issues/18#issuecomment-407540174.

**Comment by RobertFrydenlund** [comment]
It quite easy really. Just install Spicetify and enable the WebNowPlaying extension (page 2). Then switch the player type from Spotify to WebNowPlaying, and it should work out of the box.

**Comment by Permanently** [comment]
I know you're not the author of Spicetify, but since you know a bit about it - why does it only hook into the Spotify Web Player?

**Comment by Ein6tein** [comment]
From the author of Spicetify:

> WebNowplaying Websocket port in Spicetify is the same as WebNowplaying in browser, but only one is able to connect at a time. But would be later, let's debug the first problem first.

**Comment by Permanently** [comment]
Deleted my comment - turns out I'm an idiot and didn't real the instructions properly.

**Comment by hobhobuk** [comment]
Spicetify does not work at all for me..

Switched on the webnowplaying, clicked restart on Spicetify.. unless I am missing something?

**Comment by Permanently** [comment]
It'll be because you didn't activate the WebNowPlaying hook app on Spicetify. At least, that was my issue.

**Comment by hobhobuk** [comment]
No that is done.. I presume this does not work with the actual Spotify program?

Works fine if I open the browser and play via the web browser.. not really a solution though.

**Comment by Permanently** [comment]
It does work with the actual program. 
It might be a new update that I'm not aware of (I'm not at home right now) or it might just be the case of an incorrect setup. Either way, it worked for me a few days ago. 

Try making sure the Chrome/Firefox extension is active, as well as the Spicetify Default CSS being in place.

**Comment by SoDaBearJess** [comment]
I was having this issue but I just fixed it. When you change extensions you have to hit apply, but the apply button was grayed out. I hit backup and waited for that to complete, and then I was able to hit apply. Once apply was done, I could see the artist and album cover.

**Comment by tjhrulz** [comment]
While this is a very temporary fix (I do have several more changes planned and several contingency plans as well) for the time being here is a spotify plugin that will work until we get rate limited again (So don't over share/release skins that use this version)

https://cdn.discordapp.com/attachments/359027238584320002/474674288645898250/SpotifyPluginHotfix_1.0.0.rmskin

**Comment by tjhrulz** [comment]
Unless I compiled it wrong crashes will be the same as Spotify plugin

**Comment by Michael35699** [comment]
I downloaded tjhrulz's hotfix of the spotify plugin, and I can confirm that it works for me now. Thanks man! @tjhrulz

**Comment by thexmanxyz** [comment]
@tjhrulz Any way to stop rainmeter from crashing with the hot fix? :)

**Comment by Zavayy** [comment]
Are people still trying to address this problem? Or are there any other things that are similar to this that I could use?

**Comment by McGuffery** [comment]
Hopefully the problem is fixed soon, I've been wanting to try out this Program but haven't had a chance since it's been having problems

**Comment by mburnes** [comment]
Is it possible to scrape song/album/art from the Windows API for the volume banner? (i.imgur.com/PokfWba.png)
This could be a more permanent fix for that. Here's some possible info for the win10 api https://docs.microsoft.com/en-us/windows/desktop/properties/music-bumper

**Comment by thexmanxyz** [comment]
@mburnes That might be a fix, the question is how the Windows 10 API scrapes the info / or how Spotify passes the info to the Windows 10 API. I have not enough knowlegde on the data exchange but this might be worth considering! Many projects depend on SpotifyPlugin but all have more or less issues depending of the features they use...as far as I know there is a new API (WebAPI) which should be replacement of the old one. But IDK if this API lacks some basic support that is necessary for the song information scrapping.

**Comment by Wist9063** [comment]
@tjhrulz Your fix kinda works for 10-20 sec, but then crashes. Also, in the logs its spamming 404 errors.

![9n18a](https://user-images.githubusercontent.com/22089269/45664514-0b8c5200-bac1-11e8-8e87-068744a982f2.png)

Error:
```
9:26:05 PM Monday, September 17, 2018
SpotifyPlugin version 2.1.7.0
Culture: en-US
OSVersion: Microsoft Windows NT 10.0.17134.0
----
 The remote server returned an error: (404) Not Found.
----
    at System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   at System.Net.WebClient.DownloadString(Uri address)
   at SpotifyPlugin.AlbumArt.GetAlbumImage(Int32 resolution, String filePath) (Monstercat-Visualizer\visualizer.ini - [MeasureProgressPrecent])
```

**Comment by tjhrulz** [comment]
As I said my fix was temporary (I forgot I posted it here) since I have been so busy I would just recommend doing spicetify as I don't foresee myself getting around to it anytime soon

**Comment by cazaman11** [comment]
If anyones having issues with getting the WebNowPlaying player to work / install correctly in Spicetify, spotify must be installed in the same drive as rainmeter.

**Comment by ColonialDagger** [comment]
To add to the above, [someone on reddit posted a full guide](https://www.reddit.com/r/Rainmeter/comments/92nfs4/for_everyone_that_is_having_problems_with_spotify/e3cmtgh/?context=10000) to get the visualizer working with Spicetify through WebNowPlaying. [Works almost flawlessly, just like prior to Spotify Plugin being discontinued](https://i.imgur.com/v31eZci.jpg). Since the switch is permanent, this issue cannot be permanently fixed, but the Spicetify workaround is likely the best fix unless WebNowPlaying is somehow implemented directly into Monstercat Visualizer.

**Comment by Nighternyx** [comment]
@ColonialDagger Holy shit that works wonderfully, I just have to install Normal Spotify for it to work! Can't thank you enough.

**Comment by Arszilla** [comment]
@ColonialDagger Whenever Spotify updates their client, WebNowPlaying breaks and you have to resetup/reapply the Spicetify though. Any fix for that?

**Comment by ColonialDagger** [comment]
> @ColonialDagger Whenever Spotify updates their client, WebNowPlaying breaks and you have to resetup/reapply the Spicetify though. Any fix for that?

Not that I particularly know of, I know longer use the skin and haven't used it for a few months.

**Comment by marcopixel** [comment]
We will remove standalone Spotify support and replace it with spicetify-cli + WebNowPlaying since this is the easiest solution and it should work as long as Spotify doesn't redesign their desktop app.

The next release will remove the option from the media player settings page and i've created an guide for people on how to install it properly.

Many thanks for @tjhrulz and @khanhas for making this even possible, huge shoutout to them.

**Guide:** https://github.com/marcopixel/Monstercat-Visualizer/wiki/WebNowPlaying-Spotify

I will keep this issue open for a few days now so people can discuss about that change, give feedback, etc..

**Comment by Ein6tein** [comment]
Works for me - thanks to all, that contributed to this fix!!!!

**Comment by DerGeileHaralt** [comment]
Works for me too. I just reinstalled everything.
Great job guys.

**Comment by Linerly** [comment]
> We will remove standalone Spotify support and replace it with spicetify-cli + WebNowPlaying since this is the easiest solution and it should work as long as Spotify doesn't redesign their desktop app.
> 
> The next release will remove the option from the media player settings page and i've created an guide for people on how to install it properly.
> 
> Many thanks for @tjhrulz and @khanhas for making this even possible, huge shoutout to them.
> 
> **Guide:** https://github.com/marcopixel/Monstercat-Visualizer/wiki/WebNowPlaying-Spotify
> 
> I will keep this issue open for a few days now so people can discuss about that change, give feedback, etc..

It didn't work for me, or did I install it wrong? It didn't show the info, it just N/A - N/A. My Spotify version is 1.1.7.13766.gf9dc3904. What should I do to fix it?
![image](https://user-images.githubusercontent.com/47475676/58741110-de5db500-843f-11e9-81a6-426846ad50f8.png)
I already installed Spicetify, of course.

**Comment by khanhas** [comment]
@Linerly 
1. Make sure you are using Spotify Desktop version, not Windows Store version.
2. What Spicetify did you use, Spicetify for Rainmeter or spicetify-cli as in the guide?
If you used spicetify-cli, it should show what was wrong in the terminal.

**Comment by Linerly** [comment]
> @Linerly
> 
> 1. Make sure you are using Spotify Desktop version, not Windows Store version.
> 2. What Spicetify did you use, Spicetify for Rainmeter or spicetify-cli as in the guide?
>    If you used spicetify-cli, it should show what was wrong in the terminal.

I'm using the Spotify Desktop version, I use spicetify-cli in the guide, nothing was wrong in Powershell.

**Comment by khanhas** [comment]
@Linerly 
- Check that you switch to WebNowPlaying player in Monstercat setting.
- If you switched already, check that you added `webnowplaying.js` in `extensions` field in config.
Run this in powershell to examine config file:
```
cat $(spicetify -c)
```
![image](https://user-images.githubusercontent.com/26436809/58743367-4974af00-8473-11e9-8df6-54901435e696.png)

If there is no `webnowplaying.js` in `extensions` field, run:
```
spicetify config extensions webnowplaying.js
spicetify apply
```

**Comment by Linerly** [comment]
> @Linerly
> 
> * Check that you switch to WebNowPlaying player in Monstercat setting.
> * If you switched already, check that you added `webnowplaying.js` in `extensions` field in config.
>   Run this in powershell to examine config file:
> 
> ```
> cat $(spicetify -c)
> ```
> 
> ![image](https://user-images.githubusercontent.com/26436809/58743367-4974af00-8473-11e9-8df6-54901435e696.png)
> 
> If there is no `webnowplaying.js` in `extensions` field, run:
> 
> ```
> spicetify config extensions webnowplaying.js
> spicetify apply
> ```

Still, didn't work. :(

**Comment by BigmacM** [comment]
I've tried everything in this thread after the update but still can't get it to work.

**Comment by Mawsonator** [comment]
To the people who it is not working maybe ensure you select the 'Web NowPlaying' media player in the settings, this fixed it for me.
![mcatCapture](https://user-images.githubusercontent.com/15985102/58996216-1cb3f500-87ef-11e9-92df-fb1f0eb0419a.PNG)

**Comment by charmarkk** [comment]
Just curious all - what's the difference between Spicetify for Rainmeter and the -cli? The Rainmeter version causes Spotify to lock up any time it updates, necessitating a reboot as there are "processes using the application" etc. That's whether or not Spicetify is disabled/rolled back before the update. Does the -cli have the same issue? Not a terrible workaround, but annoying when in the middle of something.

**Comment by marcopixel** [comment]
@charmarkk Spicetify for Rainmeter is no longer supported and may break in the future. Also it's no longer required to have Rainmeter as a dependency to have it running, so it's much smaller in size and also much better in performance. As for the update stuff, i haven't seen that issue yet but maybe @khanhas can get us more info about that.

**Comment by charmarkk** [comment]
@marcopixel Ah neat, I hadn't known that! Thanks! I'll keep an eye to see if @khanhas has anything to add. :)

**Comment by khanhas** [comment]
I don't remember getting the behaviour as you described. And I don't think Spotify hanging process has anything to do with Spicetify.

If one of Spotify processes get stuck, just run this simple  command: `ps spotify | kill` in Powershell and carry on what you are doing.

**Comment by charmarkk** [comment]
@khanhas Many thanks for the powershell command, I forget about those. Next time I encounter it, I'll see if I can document it for you [not here]. Maye the -cli will resolve that. Thanks again both of you!

**Comment by thexmanxyz** [comment]
Just reporting back that the Spicetify approach works well for me. Did the performance of Monstercat Visualizer got worse in one of the last releases because I'm noticing higher overall CPU usage when enabled.

**Comment by Linerly** [comment]
> > @Linerly
> > 
> > * Check that you switch to WebNowPlaying player in Monstercat setting.
> > * If you switched already, check that you added `webnowplaying.js` in `extensions` field in config.
> >   Run this in powershell to examine config file:
> > 
> > ```
> > cat $(spicetify -c)
> > ```
> > 
> > 
> > ![image](https://user-images.githubusercontent.com/26436809/58743367-4974af00-8473-11e9-8df6-54901435e696.png)
> > If there is no `webnowplaying.js` in `extensions` field, run:
> > ```
> > spicetify config extensions webnowplaying.js
> > spicetify apply
> > ```
> 
> Still, didn't work. :(

![image](https://user-images.githubusercontent.com/47475676/62517722-2c34d600-b852-11e9-80f5-894e06256878.png)
Hey, at least Spotify works!

**Comment by Artemesias** [comment]
> 
> 
> > > @Linerly
> > > 
> > > * Check that you switch to WebNowPlaying player in Monstercat setting.
> > > * If you switched already, check that you added `webnowplaying.js` in `extensions` field in config.
> > >   Run this in powershell to examine config file:
> > > 
> > > ```
> > > cat $(spicetify -c)
> > > ```
> > > 
> > > 
> > > ![image](https://user-images.githubusercontent.com/26436809/58743367-4974af00-8473-11e9-8df6-54901435e696.png)
> > > If there is no `webnowplaying.js` in `extensions` field, run:
> > > ```
> > > spicetify config extensions webnowplaying.js
> > > spicetify apply
> > > ```
> > 
> > 
> > Still, didn't work. :(
> 
> ![image](https://user-images.githubusercontent.com/47475676/62517722-2c34d600-b852-11e9-80f5-894e06256878.png)
> Hey, at least Spotify works!
> 
> Edit: I uninstalled Spicetify and re-install it, then I waited patiently until it's done.

How to uninstalled Spicetify and re-install it??

**Comment by niennasill** [comment]
I checked with the latest walkthrough and it seems I did everything as described but it's not working.

Btw I tried every version of Spotify and Rainmeter ( Release/Beta - 32/64 bit versions) I don't know if its matters.


* Rainmeter Version: 
![image](https://user-images.githubusercontent.com/9532627/69539884-758e6a00-0f96-11ea-84ae-77073e8820b9.png)

* OS Version: 
![image](https://user-images.githubusercontent.com/9532627/69540160-0c5b2680-0f97-11ea-86d5-9eae82f87af1.png)

* Skin Version: 
![image](https://user-images.githubusercontent.com/9532627/69540074-e3d32c80-0f96-11ea-9418-d634aee3b6b8.png)


* Spotify Version: 
![image](https://user-images.githubusercontent.com/9532627/69540002-b5555180-0f96-11ea-889c-c480ac38c86c.png)


### Additional notes/images

![image](https://user-images.githubusercontent.com/9532627/69540478-bb97fd80-0f97-11ea-9eb6-ca7529a463d4.png)

![image](https://user-images.githubusercontent.com/9532627/69540696-54c71400-0f98-11ea-8cd0-ef318ebad4e1.png)

**Comment by Ein6tein** [comment]
@niennasill - check version of Spicetify. Try to install the latest one (in my case it's 0.9.4)

**Comment by niennasill** [comment]
> @niennasill - check version of Spicetify. Try to install the latest one (in my case it's 0.9.4)

@Ein6tein - Using the latest version of Spicetify-Cli 0.9.5 but I will give try for 0.9.4. At least we can make sure.

**Comment by niennasill** [comment]
> @niennasill - check version of Spicetify. Try to install the latest one (in my case it's 0.9.4)

@Ein6tein - Using latest version of Spicetify-Cli 0.9.5 but I will give try for 0.9.4. At least we can make sure.

**Comment by niennasill** [comment]
@Ein6tein - Still the same with 0.9.4. It seems the only difference between the two editions are "Reddit and bookmark apps: glue.css missing bug".

**Comment by Novas473** [comment]
I found this error with the newest way to, supposedly, have Rainmeter and Spotify linked or whatever, but I am not sure if it is just me... Any time I do the last step, typing "spicetify backup apply", it doesn't seem to be doing the right thing... It adds an additional "\Apps" into the path of the spotify.exe.

Example... I have "C:\Users\ninja\AppData\Local\Microsoft\WindowsApps\SpotifyAB.SpotifyMusic_zpdnekdrzrea0" as my spotify_path, but when I type "spicetify backup apply", it adds an additional "\Apps" at the end of it, making it "C:\Users\ninja\AppData\Local\Microsoft\WindowsApps\SpotifyAB.SpotifyMusic_zpdnekdrzrea0\Apps", which is a non-existent folder within that location on my computer.

There a reason why it adds "\Apps" at the end of the path? And am I even understanding what it means by "spotify_path", being the application (exe file) itself, yeah?

![Issue](https://user-images.githubusercontent.com/60446186/73390268-d75e9f00-4279-11ea-906a-c69140370955.PNG)

**Comment by bluelhf** [comment]
> 
> 
> I found this error with the newest way to, supposedly, have Rainmeter and Spotify linked or whatever, but I am not sure if it is just me... Any time I do the last step, typing "spicetify backup apply", it doesn't seem to be doing the right thing... It adds an additional "\Apps" into the path of the spotify.exe.
> 
> Example... I have "C:\Users\ninja\AppData\Local\Microsoft\WindowsApps\SpotifyAB.SpotifyMusic_zpdnekdrzrea0" as my spotify_path, but when I type "spicetify backup apply", it adds an additional "\Apps" at the end of it, making it "C:\Users\ninja\AppData\Local\Microsoft\WindowsApps\SpotifyAB.SpotifyMusic_zpdnekdrzrea0\Apps", which is a non-existent folder within that location on my computer.
> 
> There a reason why it adds "\Apps" at the end of the path? And am I even understanding what it means by "spotify_path", being the application (exe file) for Spotify itself, yeah?
> 
> ![Issue](https://user-images.githubusercontent.com/60446186/73390268-d75e9f00-4279-11ea-906a-c69140370955.PNG)

Spicetify probably requires the desktop version of Spotify, not the Windows 10 version

**Comment by BlenderUser** [comment]
![billede](https://user-images.githubusercontent.com/22281511/87229386-df357a00-c3a7-11ea-9703-c08d5b7c656f.png)
I get this?

If i proceed, i need to manually add the path... No idea what to do. I have the right Media Player selected etc.

**Comment by khanhas** [comment]
@BlenderUser You are using Windows Store Spotify, please uninstall it and download installer from Spotify website.

**Comment by BlenderUser** [comment]
I actually was not! However, i decided to uninstall and reinstall it, just in case something was jacked up... I got further but now have this error:
![billede](https://user-images.githubusercontent.com/22281511/87229618-c75ef580-c3a9-11ea-82e2-fef623918139.png)

**Comment by khanhas** [comment]
Please delete the config file and run spicetify again

**Comment by BlenderUser** [comment]
> 
> 
> Please delete the config file and run spicetify again

How do i do that?

**Comment by BlenderUser** [comment]
> 
> 
> Please delete the config file and run spicetify again

It worked. I don't know what caused the initial errors or why a wrong directory was used but it works now. Thanks. On another note: I accidentally pasted the command that changed the theme (brain fart moment). How do i reverse this?

**Comment by khanhas** [comment]
Read the help text: `spicetify -h`

**Comment by superman55555** [comment]
![image](https://user-images.githubusercontent.com/68685835/88267577-5389ea80-ccd1-11ea-930c-c8abfe21bce9.png)

I get an error when applying Spicetify and the visualizer won't show my Spotify pictures etc. still.

**Comment by SanThes123** [comment]
So I'm using Youtube music on my Chrome. I downloaded the extension and got the bar and song name and artist to show, but no luck with the cover. Any help?

**Comment by Ferociousn** [comment]
I installed everything correctly. Set mediaplayer to webnowplaying. But visualizer still cant access the spotify. Any help?

**Comment by huntahs** [comment]
Hey guys! If anyone's cover information has stopped showing, I found a solution.

Head to Powershell. Type "spicetify apply". 

Powershell in my case told me my spotify was updated, and I should run "spicetify backup apply" . I asked me to confirm I wanted to run it by typing "y". Then, everything worked again!

**Comment by ShevikWombat** [comment]
I have same problem as Ferociousn, Ihave installed everything correctly, but it still not showing song info on screen
![Annotation 2022-01-16 124302](https://user-images.githubusercontent.com/58656496/149650929-4c5b81dc-1d1b-4945-a539-233b691aaf08.jpg)
.


Spotify Version : Spotify for Windows
1.1.76.447.g11f432d8

**Comment by ItsAGeBa** [comment]
For those who still haven't gotten this fixed I followed this Reddit comment: https://www.reddit.com/r/Rainmeter/comments/hn7b0k/monstercat_visualizer_spotify/
Instant fix for me it might help you guys
I got song info, artist, song cover, pause/play, next/previous
